name: CI - Tests

on:
  push:
    branches:
      - feat/tests-setup
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run tests
        run: mvn -B -e -V -DskipITs -DskipIT -Dskip-integration-tests test

