name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feat/tests-setup ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with coverage (JaCoCo)
        run: mvn -B -q test

      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

  require-tests:
    if: github.event_name == 'pull_request'
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All tests passed; PR can be merged."

